apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  mysql-root-password: bmV3cGFzc3dvcmQxMjM=
  mysql-database: bXlhcHBkYg==
  mysql-user: ZGJ1c2Vy
  mysql-password: YXBwcGFzczEyMw==